### ISSUE TITLE
M4 issue: delay(Duration) throws an error

### ISSUE THREAD

**Issue by ypujante** [JetBrains/compose-jb#736]
After upgrading to M4 / 0.4.0 (from M3 0.3.0), the following code fails:

```
    Window(title = "Test") {
      LaunchedEffect(Unit) {
        delay(Duration.seconds(1))
        println("after delay")
      }
      Text("Hello world")
    }
```

with the following error

```
Caused by: java.lang.NoSuchMethodError: kotlinx/coroutines/DelayKt.delay-p9JZ4hM(JLkotlin/coroutines/Continuation;)Ljava/lang/Object; (loaded from file:/Volumes/Vault/Caches/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.4.3/1051e11eb789ed1df93412bebe0f06e9d29160e4/kotlinx-coroutines-core-jvm-1.4.3.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@a495ce4a) called from class MainKt$main$2$1$1 (loaded from ... by jdk.internal.loader.ClassLoaders$AppClassLoader@a495ce4a).
```

Note that it works with `delay(1000)`

**Comment by olonho** [comment]
Interestingly, it fails with code like that, if Compose plugin is applied:
```
@ExperimentalTime
fun main() {
    runBlocking {
        launch {
            repeat(1000) { i ->
                println("job: I'm sleeping $i ...")
                delay(Duration.seconds(1))
            }
        }
    }
}```

**Comment by olonho** [comment]
Seems depends on version of `kotlinx-coroutines-core`. Fails with 1.4.x, and works with 1.5.0. And Compose uses 1.4.3.

**Comment by olonho** [comment]
Seems depends on version of `kotlinx-coroutines-core`. Fails with 1.4.x, and works with 1.5.0. And Compose uses 1.4.3.

**Comment by olonho** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/1717755 promotes Compose to 1.5.0.

**Comment by olonho** [comment]
@ypujante please try 
```
dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0")
    implementation(compose.desktop.currentOs)
}
```
in your `build.gradle.kts`.

**Comment by ypujante** [comment]
I confirm that it works with this change. Another workaround is to do `Duration.seconds(1).inWholeMilliseconds` which does not introduce a dependency on a different version of couroutines.

**Comment by hfhbd** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/2649

**Comment by akurasov** [comment]
Seems it is fixed. Reopen if not.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5382">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
